<template>
  <div>
    <div class="vue-grid-item cssTransforms" style="transform: translate3d(10px, 10px, 0); width: 500px; height: 430px; position: absolute;">
      <!-- start CRM page block -->
      <div class="gridblock_contents">
        <div class="blockname">Twitter Timeline</div>
        <div class="block_header"></div>
        <div class="form_row">
          <a class="twitter-timeline"
            href="https://twitter.com/TwitterDev"
            data-height="400"
            data-chrome="nofooter"
            data-link-color="#820bbb"
            data-border-color="#a80000">
          </a>
        </div>
      </div>
      <!-- end CRM page block -->
    </div>

    <div class="vue-grid-item cssTransforms" style="transform: translate3d(520px, 10px, 0); width: 500px; height: 430px; position: absolute;">
      <!-- start CRM page block 2 -->
      <div class="gridblock_contents">
        <div class="blockname">Twitter List feed</div>
        <div class="block_header">This is a feed generated by a public list. Everyone can make their own curated lists, so we're not stuck to following only handles.</div>
        <div class="form_row">
          <a class="twitter-timeline"
            href="https://twitter.com/TwitterDev/lists/national-parks?ref_src=twsrc%5Etfw"
            data-height="400"
            data-chrome="nofooter"
            data-link-color="#820bbb"
            data-border-color="#a80000">
          </a>
        </div>
      </div>
      <!-- end CRM page block 2 -->
    </div>
  </div>
</template>

<script>
export default {
  mounted () {
    let twitterScript = document.createElement('script')
    twitterScript.setAttribute('src', 'https://platform.twitter.com/widgets.js')
    document.head.appendChild(twitterScript)
  },
}
</script>
