kind: pipeline
name: "Test & Build"
type: docker

steps:
  - name: Dependencies
    image: cortezaproject/corteza-webapp-builder
    commands: [ "yarn install" ]

  - name: Lint
    image: cortezaproject/corteza-webapp-builder
    commands: [ "yarn lint" ]

  - name: Test
    image: cortezaproject/corteza-webapp-builder
    commands: [ "yarn test:unit" ]

  - name: Build
    image: cortezaproject/corteza-webapp-builder
    commands: [ "yarn build" ]

  - name: Pack
    when: { ref: [ "refs/heads/master", "refs/heads/beta", "refs/heads/feature-*", "refs/tags/20??.*.*" ] }
    image: cortezaproject/corteza-webapp-builder
    volumes: [ { name: webapp-build, path: /var/build} ]
    commands:  [ "tar -cjf /var/build/$DRONE_REPO_NAME-${DRONE_TAG=${DRONE_BRANCH}}.tar.bz2 -C dist/ ." ]

  - name: Trigger build merge
    when: { ref: [ "refs/heads/master", "refs/heads/beta", "refs/heads/feature-*", "refs/tags/20??.*.*" ] }
    image: plugins/downstream
    commands: []
    settings:
      fork: true
      server: https://drone.crust.tech
      token: { from_secret: drone_token }
      params: [ "APP_VERSION=${DRONE_TAG=${DRONE_BRANCH}}" ]
      repositories:
        # Dynamically constructs Drone repo name that will be notified
        - "${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME%%-compose}@${DRONE_BRANCH}"

volumes:
  - name: webapp-build
    host:
      path: /var/build/drone/webapp-build
