export { default as Automation } from './../View/Automation'
export { default as Record } from './Record'
export { default as RecordList } from './../View/RecordList'
export { default as Chart } from './../View/Chart'
export { default as Content } from './../View/Content'
export { default as SocialFeed } from './../View/SocialFeed'
