name: snapshot

on:
  push:
    branches:
      - 2021.3.x*
      - 2021.6.x*
      - 2021.9.x*
      - 2021.12.x*


jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-node-
      - run: make dep test

  snapshot-docker:
    runs-on: ubuntu-latest
    needs:
      - test
    env:
      BUILD_VERSION: ${GITHUB_SHA}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - run: docker build -t ghcr.io/cortezaproject/corteza-webapp-compose:${{ env.BUILD_VERSION }} .
        if: ${{ !env.ACT }}
      - run: docker push ghcr.io/cortezaproject/corteza-webapp-compose:${{ env.BUILD_VERSION }}
        if: ${{ !env.ACT }}
